---
title: "Exploratory Data Analysis Medtronic Patents"
author: "Wranglers"
date: "Thursday, October 01, 2015"
output: html_document
---

```{r, message=FALSE}
# load libraries
library(dplyr)
library(ggplot2)
library(tidyr)
library(knitr)
library(stringr)

# load mined .csv
setwd('~/DSBA-6100/DSBA6100-GrpProject/')
patent_file <- 'medtronic_and_competitor_patents_05-15.csv'
patents <- read.csv(patent_file, stringsAsFactors=FALSE, na.strings="None")

# extract main classification
patents <- mutate(patents, patent_class = str_trim(patent_class)) %>%
    mutate(main_classification = str_sub(patent_class, 1, 3))

# load classification codes
class_code <- read.csv('patent_classification_lookup_table.csv',
                       stringsAsFactors = FALSE,
                       na.strings = "None")
names(class_code) <- c("main_classification", "class_description")

# join patents and classification codes
patents <- left_join(patents, class_code)
```

How many patent classifications were missed?
```{r}
# missed by regular expression
sum(is.na(patents$patent_class))

# missed by pulling first three characters
sum(is.na(patents$class_description))
mean(is.na(patents$class_description))
```

```{r}
# define uspto patent counts
med_actual <- c(257, 306, 317, 214 + 18, 286 + 46, 525 + 74, 
                522 + 49, 581 + 117, 668 + 808, 723 + 700, 151 + 216)
stryker_actual <- c(33, 30, 27, 31, 48, 65, 82, 94, 116, 117, 21)
bs_actual <- c(86, 146, 156, 192, 274, 474, 507, 477, 504, 561, 100)
abbott_actual <- c(54, 101, 85, 101, 115, 253, 433, 505, 508, 449, 76)

# count mined patents by company by year
patent_counts <- patents %>% 
    group_by(company_name, year_granted) %>% 
    summarise(mined = n()) 
patent_counts$uspto <- c(abbott_actual, bs_actual, med_actual, stryker_actual)

# compare mined patent counts to reported USPTO patent counts
patent_ratios <- gather(patent_counts, "source_found", "count", 3:4)
# names(patent_ratios)[3:4] <- c("source_found","count")
```

```{r}
# visualize ratios by year
plot_ratios <- ggplot(patent_ratios, aes(company_name, count, fill=source_found)) +
    geom_bar(stat='identity', position='dodge') +
    facet_grid(.~year_granted, scales="free_y") +
    labs(list(title = "Patent Counts: Biblio Data vs USPTO",
              x = "Company Name",
              y = "Number of Patents")) +
    theme(axis.text.x = element_text(angle=90, hjust=1, vjust=0.5))
plot_ratios
```

```{r}
# visualize ratios: total by company
plot_totals <- ggplot(patent_ratios, aes(reorder(company_name, count), 
                                         count, fill=source_found)) +
    geom_bar(stat='identity', position='dodge') +
    labs(list(title = "Patent Counts: Biblio Data vs USPTO",
              x = "Company Name",
              y = "Number of Patents")) +
    theme(title = element_text(size = 16))
plot_totals
```

```{r, message=FALSE, warning=FALSE}
library(wordcloud)   # Package for word clouds
library(wesanderson) # color palettes
library(RWeka)       # NLP (n-grams)
library(tm)          # text mining
library(slam)        # for simple triplet matrix algebra

# filter company equal to Medtronic
med <- patents %>% filter(company_name == 'Medtronic')

# process abstracts for visualization
abstracts <- VCorpus(VectorSource(med$patent_abstract))
abstracts <- tm_map(abstracts, content_transformer(tolower))
abstracts <- tm_map(abstracts, removeWords, stopwords("english"))

# count trigrams for abstracts
count_ngrams <- function(n, corp) {
    options(mc.cores = 2)
    ctrl <- Weka_control(min = n, max = n)
    ngram_tokenizer <- function(x) NGramTokenizer(x, control = ctrl)
    tdm_ngram <- TermDocumentMatrix(corp, 
                                    control = list(tokenize = ngram_tokenizer))
    return(tdm_ngram)
}
abstract_trigrams <- count_ngrams(3, abstracts)
# abstract_trigrams <- removeSparseTerms(abstract_trigrams, 0.4)
wc <- row_sums(abstract_trigrams)
abstract_wc <- data.frame(trigram = names(wc), count = wc)

# visualize abstracts
wordcloud(abstract_wc$trigram, abstract_wc$count, scale=c(2, .5), min.freq=50, random.order=FALSE, colors=palette)

# visualize patent titles
palette <- wes_palette("Darjeeling", 10, "continuous")
palette <- palette[10:1]
wordcloud(med$patent_title, max.words=150, colors=palette)
```

```{r}
# Visualize patent classifications
class_counts <- patents %>%
    group_by(class_description) %>%
    summarise(n = n()) %>%
    filter(is.na(class_description) == FALSE)
class_counts_top10 <- filter(class_counts, 
                       n >= quantile(class_counts$n, >= .90))
class_counts_ppt <- arrange(class_counts, desc(n))[1:8,]

# plot all companies, change to ...ppt for presentation
plot_class_all <- ggplot(class_counts_ppt, 
                         aes(reorder(class_description, n), n)) + 
    geom_bar(stat="identity", fill="#FD6467") +
    labs(x = "Main Patent Classification", y = "Count") +
    coord_flip() +
    ggtitle("Top Patent Classes All Companies")
plot_class_all

# plot by company
class_cts_by_co <- patents %>%
    group_by(company_name, class_description) %>%
    summarise(n = n()) %>%
    filter(is.na(class_description) == FALSE)
class_cts_by_co <- filter(class_cts_by_co, 
                          n >= quantile(class_cts_by_co$n, .90),
                          is.na(class_description) == FALSE)
by_co_ppt <- filter(class_cts_by_co, class_description %in% class_counts_ppt$class_description)

plot_class_co <- ggplot(by_co_ppt,
                        aes(reorder(class_description, n),
                            n,
                            fill = company_name)) +
    geom_bar(stat = "identity", position = "dodge") +
    guides(fill = guide_legend(reverse=TRUE)) +
    labs(x = "Main Patent Classification", 
         title="Top Patent Classes by Company") +
    coord_flip()
plot_class_co

# plot medtronic only
class_ct_med <- med %>%
    filter(is.na(class_description) == FALSE) %>%
    group_by(class_description) %>%
    summarise(n = n(), proportion = n()/nrow(med))
class_ct_med <- filter(class_ct_med, n >= quantile(class_ct_med$n, .75))
med_ct_ppt <- arrange(class_ct_med, desc(n))[1:4,]

plot_med_class <- ggplot(med_ct_ppt,
                         aes(reorder(class_description, n), proportion)) +
    geom_bar(stat="identity", fill="#5BBCD6") +
    labs(x = "Main Patent Classification",
         title = "Top Patent Classes for Medtronic") +
    coord_flip()
plot_med_class

# proportions of top n patent classes
sorted_by_prop <- arrange(class_ct_med, desc(proportion)) %>%
    mutate(cumulative_sum = proportion)
for(i in 2:nrow(sorted_by_prop)){
    sorted_by_prop[i,4] <- sum(sorted_by_prop[i, 3], sorted_by_prop[i - 1, 4])
}
# plot
plot_prop <- ggplot(sorted_by_prop, 
                    aes(reorder(class_description, n), cumulative_sum)) +
    geom_bar(stat="identity", fill="#5BBCD6") +
    coord_flip()
plot_prop
```